# /// script
# requires-python = ">=3.11"
# dependencies = ["numpy>=1.26"]
# ///
"""Recompute monophone distance tables from the Julius dictation-kit HMMs.

The bundled biphone tables were originally derived from the Julius acoustic
model following the method in
https://yaamaa-memo.hatenablog.com/entry/2017/12/17/062435 : the distance
from phoneme A to phoneme B is how unlikely samples generated by A's HMM are
under B's HMM (an asymmetric, likelihood-based distance).

This script re-applies that idea directly to the monophone GMM-HMMs
(model/phone_m/jnas-mono-16mix-gid.hmmdefs: 3 emitting states x 16 diagonal
Gaussian mixtures x 25-dim MFCC). Instead of sampling variable-length state
sequences (which made the original values length-dependent and required an
ad-hoc correction), the distance is the per-frame Monte Carlo cross-entropy
averaged over aligned emitting states:

    d(A, B) = -(1/S) * sum_s mean_i[ log p_{B,s}(x_i) ],  x_i ~ GMM_{A,s}

Like the original tables it is asymmetric with a non-zero diagonal;
subtracting the diagonal (kanasim's same_phonome_offset, on by default)
turns it into a Monte Carlo estimate of the state-averaged KL divergence.

Requires the dictation-kit checkout (see README) next to the repository
root; the resulting CSVs are committed so users do not need it.

Usage:
    uv run scripts/create_hmm_distance_csv.py
"""

import argparse
import csv
import os

import numpy as np

DEFAULT_HMMDEFS = os.path.join(
    os.path.dirname(__file__),
    "../dictation-kit/model/phone_m/jnas-mono-16mix-gid.hmmdefs",
)
DEFAULT_OUTPUT_DIR = os.path.join(
    os.path.dirname(__file__), "../src/kanasim/data/monophone"
)

CONSONANTS = [
    "b", "by", "ch", "d", "dy", "f", "g", "gy", "h", "hy", "j", "k", "ky",
    "m", "my", "n", "ny", "p", "py", "r", "ry", "s", "sh", "sp", "t", "ts",
    "w", "y", "z",
]  # fmt: skip
VOWELS = ["N", "a", "a:", "e", "e:", "i", "i:", "o", "o:", "q", "sp", "u", "u:"]

N_SAMPLES = 1000
SEED = 0


def parse_hmmdefs(path: str) -> dict[str, list[dict[str, np.ndarray]]]:
    """Parse HTK-format hmmdefs into {phone: [state, ...]} where each state is
    {"weights": (M,), "means": (M, D), "variances": (M, D)}."""
    with open(path, encoding="utf-8") as f:
        tokens = f.read().split()

    hmms: dict[str, list[dict[str, np.ndarray]]] = {}
    i = 0
    phone = None
    states: list[dict[str, np.ndarray]] = []
    mixtures: list[tuple[float, np.ndarray, np.ndarray]] = []

    def flush_state():
        if mixtures:
            weights = np.array([m[0] for m in mixtures])
            weights = weights / weights.sum()  # hmmdefs weights are rounded
            means = np.array([m[1] for m in mixtures])
            variances = np.array([m[2] for m in mixtures])
            states.append({"weights": weights, "means": means, "variances": variances})
            mixtures.clear()

    while i < len(tokens):
        token = tokens[i]
        if token == "~h":
            flush_state()
            if phone is not None:
                hmms[phone] = states
            phone = tokens[i + 1].strip('"')
            states = []
            i += 2
        elif token == "<STATE>":
            flush_state()
            i += 2
        elif token == "<MIXTURE>":
            weight = float(tokens[i + 2])
            assert tokens[i + 3] == "<MEAN>"
            dim = int(tokens[i + 4])
            mean = np.array([float(x) for x in tokens[i + 5 : i + 5 + dim]])
            j = i + 5 + dim
            assert tokens[j] == "<VARIANCE>"
            variance = np.array([float(x) for x in tokens[j + 2 : j + 2 + dim]])
            mixtures.append((weight, mean, variance))
            i = j + 2 + dim
        elif token == "<TRANSP>":
            flush_state()
            i += 1
        else:
            i += 1
    flush_state()
    if phone is not None:
        hmms[phone] = states
    return hmms


def gmm_sample(state: dict[str, np.ndarray], n: int, rng) -> np.ndarray:
    components = rng.choice(len(state["weights"]), size=n, p=state["weights"])
    means = state["means"][components]
    stds = np.sqrt(state["variances"][components])
    return rng.normal(means, stds)


def gmm_log_likelihood(state: dict[str, np.ndarray], x: np.ndarray) -> np.ndarray:
    """Log-likelihood of each row of x (N, D) under a diagonal GMM."""
    means = state["means"][None, :, :]  # (1, M, D)
    variances = state["variances"][None, :, :]
    diff = x[:, None, :] - means
    log_norm = -0.5 * (
        x.shape[1] * np.log(2 * np.pi) + np.log(state["variances"]).sum(axis=1)
    )  # (M,)
    log_probs = log_norm[None, :] - 0.5 * (diff**2 / variances).sum(axis=2)  # (N, M)
    log_probs += np.log(state["weights"])[None, :]
    max_log = log_probs.max(axis=1, keepdims=True)
    return (max_log + np.log(np.exp(log_probs - max_log).sum(axis=1, keepdims=True)))[
        :, 0
    ]


def cross_entropy_distance(
    samples_a: list[np.ndarray], states_b: list[dict[str, np.ndarray]]
) -> float:
    n_states = min(len(samples_a), len(states_b))
    total = 0.0
    for s in range(n_states):
        total += -gmm_log_likelihood(states_b[s], samples_a[s]).mean()
    return total / n_states


def compute_table(
    phones: list[str], hmms: dict[str, list[dict[str, np.ndarray]]]
) -> list[dict[str, str | float]]:
    rng = np.random.default_rng(SEED)
    samples = {p: [gmm_sample(s, N_SAMPLES, rng) for s in hmms[p]] for p in phones}
    rows = []
    for p1 in phones:
        for p2 in phones:
            distance = cross_entropy_distance(samples[p1], hmms[p2])
            rows.append({"phonome1": p1, "phonome2": p2, "distance": distance})
    return rows


def write_csv(rows: list[dict[str, str | float]], output_csv: str) -> None:
    os.makedirs(os.path.dirname(output_csv), exist_ok=True)
    with open(output_csv, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["phonome1", "phonome2", "distance"])
        writer.writeheader()
        writer.writerows(rows)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--hmmdefs", default=DEFAULT_HMMDEFS)
    parser.add_argument("-o", "--output_dir", default=DEFAULT_OUTPUT_DIR)
    args = parser.parse_args()

    hmms = parse_hmmdefs(args.hmmdefs)
    missing = [p for p in set(CONSONANTS + VOWELS) if p not in hmms]
    if missing:
        raise SystemExit(f"phones missing from hmmdefs: {missing}")

    consonant_rows = compute_table(CONSONANTS, hmms)
    write_csv(
        consonant_rows,
        os.path.join(args.output_dir, "distance_consonants_mono_hmm.csv"),
    )
    vowel_rows = compute_table(VOWELS, hmms)
    write_csv(vowel_rows, os.path.join(args.output_dir, "distance_vowels_mono_hmm.csv"))
    print(f"wrote {len(consonant_rows)} consonant rows, {len(vowel_rows)} vowel rows")
